name: elanam_reports
description: A Flutter application for generating financial reports from Elanam clinics.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mongo_dart: ^0.10.3
  provider: ^6.1.4
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  lottie: ^3.3.1
  intl: ^0.19.0
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  flutter_svg: ^2.0.17
  http: ^1.1.0
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/icons/
