name: Flutter Android Build - final - final

on:
  workflow_dispatch: # Manual trigger only

env:
  FLUTTER_VERSION: "3.10.6" # Replace with a valid Flutter version
  TARGET_PLATFORM: "android-arm64"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install XML tools
        run: sudo apt-get install -y libxml2-utils

      - name: Validate original AndroidManifest.xml
        run: |
          if ! xmllint --noout android/app/src/main/AndroidManifest.xml; then
            echo "::error::Original AndroidManifest.xml has syntax errors"
            exit 1
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Manually Install Flutter
        run: |
          # Download and extract Flutter SDK
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
          tar xf flutter_linux_${FLUTTER_VERSION}-stable.tar.xz
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Build Release APK
        run: |
          flutter pub get
          flutter build apk --release \
            --target-platform ${{ env.TARGET_PLATFORM }} \
            --dart-define=FLUTTER_BUILD_MODE=release \
            --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
